# 服务端口
server:
  port: 8150

### spring 配置
spring:
  application:
    #服务名
    name: service_user
    #环境设置：dev 开发环境、test 测试环境、prod 生产环境
  profiles:
    active: dev
## mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
## 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
## redis
  redis:
    host: 192.168.1.1
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        max-idle: 5
        min-idle: 0
  cloud:
    nacos:
      discovery:
        #nacos服务地址
        server-addr: 127.0.0.1:8848
## 配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:com/atguigu/yygh/user/mapper/xml/*.xml

